[phases.setup]
nixPkgs = [
  "...",
  "chromium",
  "glib",
  "nspr",
  "nss",
  "atk",
  "at-spi2-atk",
  "at-spi2-core",
  "cups",
  "dbus",
  "libdrm",
  "gtk3",
  "pango",
  "cairo",
  "alsa-lib",
  "mesa",
  "libGL",
  "libglvnd",
  "udev",
  "zlib",
  "libxkbcommon",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "xorg.libxcb",
  "xorg.libXcursor",
  "xorg.libXi",
  "xorg.libXrender",
  "xorg.libXtst",
  "expat",
  "fontconfig",
  "freetype"
]
nixLibs = [
  "...",
  "glib",
  "nspr",
  "nss",
  "atk",
  "at-spi2-atk",
  "at-spi2-core",
  "cups",
  "dbus",
  "libdrm",
  "gtk3",
  "pango",
  "cairo",
  "alsa-lib",
  "mesa",
  "libGL",
  "libglvnd",
  "udev",
  "zlib",
  "libxkbcommon",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "xorg.libxcb",
  "xorg.libXcursor",
  "xorg.libXi",
  "xorg.libXrender",
  "xorg.libXtst",
  "expat",
  "fontconfig",
  "freetype"
]

[variables]
PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS = "true"


