[project]
name = "scraping"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "santhoshg2004", email = "santhoshyadav430@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "curl-cffi>=0.16.3",
    "lxml>=6.1.3",
    "playwright>=1.63.0",
    "playwright-stealth>=2.0.3",
    "requests>=2.34.2",
    "tqdm>=4.70.1",
]

[project.scripts]
scraping = "scraping:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
